import type {
  CryptoProvider,
  KeyPair,
  SecurityMode,
  DeviceIdentity,
  AuthRequest,
  AuthResponse,
  EncryptedKeyEnvelope,
} from '../security/types.js';
import { defaultCryptoProvider } from '../security/crypto-provider.js';
import { SessionSecurityContext, deriveSessionKeys } from '../security/security-context.js';
import { AuthorizationManager } from '../security/authorization.js';
import { TransportPacket } from '../packet/types.js';
import { PacketDeduplicator } from '../packet/deduplicator.js';
import { FileBlocker, FileManifest } from '../transfer/blocker.js';
import { FileReassembler, ReassemblyResult } from '../transfer/reassembler.js';
import { LtEncoder } from '../fec/lt-encoder.js';
import { LtDecoder } from '../fec/lt-decoder.js';
import type { SessionAnnouncement, SessionState } from './types.js';

export const FLAG_ENCRYPTED = 0x02;

/**
 * Sender-side session orchestrator managing key agreement, authorization,
 * FEC symbol generation, and AEAD packet encryption.
 */
export class SenderSession {
  readonly manifest: FileManifest;
  readonly mode: SecurityMode;
  readonly senderIdentity: DeviceIdentity;
  readonly ephemeralKeyPair: KeyPair;
  readonly masterSharedSecret: Uint8Array;
  readonly securityContext: SessionSecurityContext;
  readonly authManager: AuthorizationManager;
  readonly encoder: LtEncoder;
  readonly crypto: CryptoProvider;

  private readonly blocks: ReturnType<FileBlocker['partition']>['blocks'];
  private state: SessionState = 'announcing';

  constructor(
    manifest: FileManifest,
    blocks: ReturnType<FileBlocker['partition']>['blocks'],
    mode: SecurityMode,
    senderIdentity: DeviceIdentity,
    crypto: CryptoProvider = defaultCryptoProvider,
  ) {
    this.manifest = manifest;
    this.blocks = blocks;
    this.mode = mode;
    this.senderIdentity = senderIdentity;
    this.crypto = crypto;

    // Generate ephemeral X25519 keypair for session forward secrecy
    this.ephemeralKeyPair = this.crypto.generateKeyPair();

    // In BOTH Quick Send and Private Send, the master secret is a fresh,
    // cryptographically random 256-bit key generated by the sender.
    // It is NEVER derived from public announcement values.
    this.masterSharedSecret = this.crypto.randomBytes(32);

    // Derive active AEAD session keys
    const sessionKeys = deriveSessionKeys(
      this.masterSharedSecret,
      manifest.sessionId,
      mode,
      this.crypto,
    );

    this.securityContext = new SessionSecurityContext(
      manifest.sessionId,
      mode,
      sessionKeys,
      this.crypto,
    );

    this.authManager = new AuthorizationManager(
      manifest.sessionId,
      mode,
      this.ephemeralKeyPair.privateKey,
      this.ephemeralKeyPair.publicKey,
      this.masterSharedSecret,
      this.crypto,
    );

    this.encoder = new LtEncoder();
    this.state = mode === 'quick' ? 'transmitting' : 'authorizing';
  }

  get currentState(): SessionState {
    return this.state;
  }

  /**
   * Generates the public session announcement message broadcast over the visual channel.
   */
  getAnnouncement(): SessionAnnouncement {
    return {
      sessionId: this.manifest.sessionId,
      mode: this.mode,
      senderDeviceId: this.senderIdentity.deviceId,
      senderPublicKey: this.ephemeralKeyPair.publicKey,
      fileName: this.manifest.fileName,
      fileSize: this.manifest.fileSize,
      sha256Digest: this.manifest.sha256Digest,
      symbolSize: this.manifest.symbolSize,
      symbolsPerBlock: this.manifest.symbolsPerBlock,
      totalBlocks: this.manifest.totalBlocks,
      timestamp: Date.now(),
    };
  }

  /**
   * Handles an authorization request from a prospective receiver.
   * In Quick Send, automatically returns an authorized AuthResponse containing
   * the receiver's encrypted key envelope.
   */
  handleAuthRequest(req: AuthRequest): AuthResponse {
    return this.authManager.handleAuthRequest(req);
  }

  /**
   * Approves a receiver for Private Send and returns their encrypted key envelope.
   */
  approveReceiver(receiverDeviceId: string): AuthResponse {
    const res = this.authManager.approveReceiver(receiverDeviceId);
    this.state = 'transmitting';
    return res;
  }

  /**
   * Denies access to a receiver for Private Send.
   */
  rejectReceiver(receiverDeviceId: string, reason?: string): AuthResponse {
    return this.authManager.rejectReceiver(receiverDeviceId, reason);
  }

  /**
   * Encodes and AEAD-encrypts an encoded symbol into a ready-to-transmit TransportPacket.
   */
  generateEncryptedPacket(blockIndex: number, symbolId: number): TransportPacket {
    const block = this.blocks[blockIndex];
    if (!block) {
      throw new RangeError(`Block index ${blockIndex} out of bounds`);
    }

    const sourceSymbols = LtEncoder.partitionSourceSymbols(block);
    const encSym = this.encoder.encodeSymbol(block, sourceSymbols, symbolId);

    // Encrypt raw symbol payload with AAD binding to packet metadata
    const wirePayload = this.securityContext.encryptToWirePayload(
      blockIndex,
      symbolId,
      encSym.data,
      2, // DATA packet
      FLAG_ENCRYPTED,
      'sender', // Sender outbound
    );

    return {
      protocolVersion: 1,
      packetType: 'data',
      flags: FLAG_ENCRYPTED,
      sessionId: this.manifest.sessionId,
      blockIndex,
      symbolId,
      fecMetadata: { k: block.k, degree: encSym.degree },
      payload: wirePayload,
    };
  }
}

/**
 * Receiver-side session orchestrator managing key establishment, authorization,
 * AEAD packet decryption, deduplication, and file reassembly.
 */
export class ReceiverSession {
  readonly announcement: SessionAnnouncement;
  readonly mode: SecurityMode;
  readonly receiverIdentity?: DeviceIdentity | undefined;
  readonly crypto: CryptoProvider;
  readonly deduplicator: PacketDeduplicator;
  readonly decoder: LtDecoder;
  readonly reassembler: FileReassembler;

  private securityContext?: SessionSecurityContext | undefined;
  private state: SessionState;

  private constructor(
    announcement: SessionAnnouncement,
    receiverIdentity?: DeviceIdentity | undefined,
    crypto: CryptoProvider = defaultCryptoProvider,
  ) {
    this.announcement = announcement;
    this.mode = announcement.mode;
    this.receiverIdentity = receiverIdentity;
    this.crypto = crypto;
    this.deduplicator = new PacketDeduplicator();
    this.decoder = new LtDecoder();

    const manifest: FileManifest = {
      sessionId: announcement.sessionId,
      fileName: announcement.fileName,
      fileSize: announcement.fileSize,
      mimeType: 'application/octet-stream',
      sha256Digest: announcement.sha256Digest,
      symbolSize: announcement.symbolSize,
      symbolsPerBlock: announcement.symbolsPerBlock,
      totalBlocks: announcement.totalBlocks,
    };
    this.reassembler = new FileReassembler(manifest);
    this.state = 'idle';
  }

  get currentState(): SessionState {
    return this.state;
  }

  /**
   * Initializes a Quick Send receiver session.
   * If no receiverIdentity is provided, creates an ephemeral identity for key agreement.
   */
  static createQuickSend(
    announcement: SessionAnnouncement,
    receiverIdentity?: DeviceIdentity | undefined,
    crypto: CryptoProvider = defaultCryptoProvider,
  ): ReceiverSession {
    if (announcement.mode !== 'quick') {
      throw new Error(`Announcement mode is ${announcement.mode}, expected 'quick'`);
    }

    const identity: DeviceIdentity = receiverIdentity ?? {
      deviceId: `quick-rcv-${Date.now()}-${Math.floor(Math.random() * 1000000)}`,
      keyPair: crypto.generateKeyPair(),
    };

    const session = new ReceiverSession(announcement, identity, crypto);
    session.state = 'authorizing';
    return session;
  }

  /**
   * Initializes a Private Send receiver session (requires key envelope to proceed).
   */
  static createPrivateSend(
    announcement: SessionAnnouncement,
    receiverIdentity: DeviceIdentity,
    crypto: CryptoProvider = defaultCryptoProvider,
  ): ReceiverSession {
    if (announcement.mode !== 'private') {
      throw new Error(`Announcement mode is ${announcement.mode}, expected 'private'`);
    }

    const session = new ReceiverSession(announcement, receiverIdentity, crypto);
    session.state = 'authorizing';
    return session;
  }

  /**
   * Generates an AuthRequest to present to the sender in either Quick Send or Private Send mode.
   */
  createAuthRequest(): AuthRequest {
    if (!this.receiverIdentity) {
      throw new Error('Receiver identity required to create authorization request');
    }
    return {
      sessionId: this.announcement.sessionId,
      receiverDeviceId: this.receiverIdentity.deviceId,
      receiverPublicKey: this.receiverIdentity.keyPair.publicKey,
      timestamp: Date.now(),
    };
  }

  /**
   * Applies an approved encrypted key envelope, unlocking AEAD decryption capability.
   */
  applyKeyEnvelope(envelope: EncryptedKeyEnvelope): void {
    if (!this.receiverIdentity) {
      throw new Error('Receiver identity required to unwrap key envelope');
    }

    const masterSharedSecret = AuthorizationManager.unwrapKeyEnvelope(
      envelope,
      this.receiverIdentity.keyPair.privateKey,
      this.announcement.sessionId,
      this.crypto,
    );

    const sessionKeys = deriveSessionKeys(
      masterSharedSecret,
      this.announcement.sessionId,
      this.mode,
      this.crypto,
    );

    this.securityContext = new SessionSecurityContext(
      this.announcement.sessionId,
      this.mode,
      sessionKeys,
      this.crypto,
    );

    this.state = 'receiving';
  }

  /**
   * Convenience helper to apply key envelope directly from an AuthResponse.
   */
  establishFromAuthResponse(response: AuthResponse): void {
    if (!response.keyEnvelope) {
      throw new Error('AuthResponse does not contain an encrypted key envelope');
    }
    this.applyKeyEnvelope(response.keyEnvelope);
  }

  /**
   * Processes an incoming transport packet: deduplication, AEAD decryption,
   * replay verification, and peeling decoding.
   *
   * @returns true if packet was successfully decrypted and provided useful novel data
   */
  processPacket(packet: TransportPacket): boolean {
    if (!this.securityContext) {
      throw new Error('Session security context not established. Awaiting authorization.');
    }

    // Step 1: Pre-decryption deduplication filter
    if (!this.deduplicator.process(packet)) {
      return false; // Duplicate symbol dropped
    }

    // Step 2: AEAD Decryption and AAD verification
    // Throws DecryptionError if tag or ciphertext is tampered.
    // Throws ReplayError if sequence number was replayed.
    const decryptedSymbolData = this.securityContext.decryptFromWirePayload(
      packet.blockIndex,
      packet.symbolId,
      packet.payload,
      2, // DATA packet
      packet.flags,
      true, // Enforce replay protection
      'sender', // Sender outbound -> receiver inbound
    );

    // Step 3: Dispatch decrypted payload to LT fountain decoder
    return this.decoder.addSymbol({
      blockIndex: packet.blockIndex,
      symbolId: packet.symbolId,
      k: packet.fecMetadata.k,
      degree: packet.fecMetadata.degree,
      data: decryptedSymbolData,
      isSourceSymbol: packet.fecMetadata.degree === 1,
    });
  }

  /**
   * Checks whether all source blocks of the file have been decoded.
   */
  isComplete(): boolean {
    for (let b = 0; b < this.announcement.totalBlocks; b++) {
      if (!this.decoder.isBlockComplete(b)) {
        return false;
      }
    }
    return true;
  }

  /**
   * Reassembles the final file and verifies end-to-end SHA-256 hash.
   */
  reassemble(): ReassemblyResult {
    for (let b = 0; b < this.announcement.totalBlocks; b++) {
      if (this.decoder.isBlockComplete(b)) {
        const blockBytes = this.decoder.decodeBlock(b)!;
        this.reassembler.addBlock(b, blockBytes);
      }
    }

    const result = this.reassembler.reassemble();
    this.state = 'completed';
    return result;
  }
}
