package com.lumalink.harness

import com.google.zxing.BarcodeFormat
import com.google.zxing.Result
import com.google.zxing.ResultMetadataType
import com.google.zxing.ResultPoint
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Phase 5C.1 LumaLink Packet Receiver Boundary Tests.
 *
 * Verifies:
 * - LumaPacketCodec parsing and validation
 * - IEEE 802.3 CRC-32 parity with canonical TypeScript BinaryPacketCodec
 * - Big-endian unsigned field parsing
 * - Exact Byte Mode extraction via ResultMetadataType.BYTE_SEGMENTS
 * - Strict rejection of corrupted, truncated, and malformed packets
 * - Golden vector validation against Phase 5B real wire packet fixtures
 */
class LumaPacketCodecTest {

    // =========================================================================
    // Canonical Phase 5B Real Wire Packet Fixtures
    // (from scripts/display-harness/real-packets.js generated by TypeScript core)
    // =========================================================================

    companion object {
        // Phase 5B Packet 0: 122 bytes, Block 0, Sym 0, K=16, deg=1, len=80, CRC=0x0d2f3c6f
        val PHASE_5B_PACKET_0 = byteArrayOf(
            76, 85, 77, 65, 1, 2, 2, 0, 9, -23, -103, 115, -60, 120, 68, 45, -81, 96, 43, -81, 118, -79,
            -41, -107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 1, 0, 80, 13, 47, 60, 111, 23, 23, 89, 3, 59, -46,
            89, 105, 62, -39, -85, 109, 59, -127, -80, -44, 2, -8, -74, -123, 41, -43, -87, 126, 59, 7, 96,
            -102, -10, 71, 120, -41, 36, -29, 29, 48, 23, -67, -122, -92, -110, -41, -6, 109, 90, -11, 7,
            -49, -4, 19, 86, -42, -112, -85, 95, -56, -90, 0, -104, -25, 119, -18, 71, -12, -59, 62, 63,
            -97, 2, 42, 74, 82, -110, 15, 41, 16, 70, -67, -49, -87
        )

        // Phase 5B Packet 1: 122 bytes, Block 0, Sym 1, K=16, deg=13, len=80, CRC=0x5d8da80f
        val PHASE_5B_PACKET_1 = byteArrayOf(
            76, 85, 77, 65, 1, 2, 2, 0, 9, -23, -103, 115, -60, 120, 68, 45, -81, 96, 43, -81, 118, -79,
            -41, -107, 0, 0, 0, 0, 0, 0, 0, 1, 0, 16, 0, 13, 0, 80, 93, -115, -88, 15, 123, 107, -86, -40,
            76, 92, -37, -90, -69, -5, -20, 65, 34, 36, 84, -100, 94, 42, -72, -93, -110, -45, 3, 23, -52,
            -92, -125, 122, 43, -60, -96, 33, 91, -25, 80, 53, 108, 45, -75, 30, 82, 70, 50, -83, 35, 81,
            4, 109, -58, -107, 100, 116, 71, -116, 91, 10, 108, -109, 79, -33, -11, -61, -117, -10, 109, -110,
            14, 9, -60, -33, -57, -88, 47, 18, 117, 127, -1, 107, -86, -106
        )

        const val EXPECTED_SESSION_ID = "09e99973-c478-442d-af60-2baf76b1d795"
    }

    // =========================================================================
    // A. Valid Packet Test
    // =========================================================================

    @Test
    fun testValidPhase5bPacket0Parsing() {
        val packet = LumaPacketCodec.decode(PHASE_5B_PACKET_0)

        assertEquals(1, packet.version)
        assertEquals(LumaPacketCodec.TYPE_DATA, packet.packetType)
        assertEquals("DATA", packet.packetTypeName)
        assertEquals(2, packet.flags)
        assertTrue(packet.isEncrypted)
        assertEquals(0, packet.reserved)

        assertEquals(EXPECTED_SESSION_ID, packet.sessionIdUuid)
        assertEquals("09e99973c478442daf602baf76b1d795", packet.sessionIdHex)
        assertEquals(0L, packet.blockIndex)
        assertEquals(0L, packet.symbolId)
        assertEquals(16, packet.k)
        assertEquals(1, packet.degree)
        assertEquals(80, packet.payloadLength)
        assertEquals(0x0d2f3c6fL, packet.crc32)

        assertEquals(80, packet.payload.size)
        assertEquals(122, packet.rawBytes.size)

        // Verify first and last bytes of payload survive intact
        assertEquals(23, packet.payload[0].toInt() and 0xFF)
        assertEquals(169, packet.payload[79].toInt() and 0xFF)
    }

    @Test
    fun testValidPhase5bPacket1Parsing() {
        val packet = LumaPacketCodec.decode(PHASE_5B_PACKET_1)

        assertEquals(1, packet.version)
        assertEquals(LumaPacketCodec.TYPE_DATA, packet.packetType)
        assertEquals("DATA", packet.packetTypeName)
        assertEquals(EXPECTED_SESSION_ID, packet.sessionIdUuid)
        assertEquals(0L, packet.blockIndex)
        assertEquals(1L, packet.symbolId)
        assertEquals(16, packet.k)
        assertEquals(13, packet.degree)
        assertEquals(80, packet.payloadLength)
        assertEquals(0x5d8da80fL, packet.crc32)
        assertEquals(80, packet.payload.size)
        assertEquals(122, packet.rawBytes.size)
    }

    // =========================================================================
    // B. CRC Corruption Test
    // =========================================================================

    @Test
    fun testRejectCorruptedPayloadByte() {
        val corrupted = PHASE_5B_PACKET_0.copyOf()
        // Corrupt first byte of payload (index 42)
        corrupted[42] = (corrupted[42].toInt() xor 0x01).toByte()

        try {
            LumaPacketCodec.decode(corrupted)
            fail("Expected ChecksumMismatchException")
        } catch (e: ChecksumMismatchException) {
            assertEquals(0x0d2f3c6fL, e.expected)
            assertTrue("Actual checksum must differ from expected", e.actual != e.expected)
        }
    }

    @Test
    fun testRejectCorruptedLastPayloadByte() {
        val corrupted = PHASE_5B_PACKET_0.copyOf()
        // Corrupt last byte of payload (index 121)
        corrupted[121] = (corrupted[121].toInt() xor 0xFF).toByte()

        try {
            LumaPacketCodec.decode(corrupted)
            fail("Expected ChecksumMismatchException")
        } catch (e: ChecksumMismatchException) {
            assertEquals(0x0d2f3c6fL, e.expected)
        }
    }

    // =========================================================================
    // C. Header Corruption Test
    // =========================================================================

    @Test
    fun testRejectCorruptedHeaderPrefix() {
        // Corrupt degree (byte 35)
        val corrupted = PHASE_5B_PACKET_0.copyOf()
        corrupted[35] = 99.toByte()

        try {
            LumaPacketCodec.decode(corrupted)
            fail("Expected ChecksumMismatchException")
        } catch (e: ChecksumMismatchException) {
            assertEquals(0x0d2f3c6fL, e.expected)
        }
    }

    @Test
    fun testRejectCorruptedSessionIdByte() {
        // Corrupt byte 10 inside session ID
        val corrupted = PHASE_5B_PACKET_0.copyOf()
        corrupted[10] = (corrupted[10].toInt() xor 0x42).toByte()

        try {
            LumaPacketCodec.decode(corrupted)
            fail("Expected ChecksumMismatchException")
        } catch (e: ChecksumMismatchException) {
            assertEquals(0x0d2f3c6fL, e.expected)
        }
    }

    // =========================================================================
    // D. Bad Magic Test
    // =========================================================================

    @Test
    fun testRejectBadMagic() {
        val corrupted = PHASE_5B_PACKET_0.copyOf()
        corrupted[0] = 'X'.code.toByte()

        try {
            LumaPacketCodec.decode(corrupted)
            fail("Expected MalformedPacketException")
        } catch (e: MalformedPacketException) {
            assertTrue(e.message?.contains("expected 'LUMA'") == true)
        }
    }

    // =========================================================================
    // E. Truncated Packet Test
    // =========================================================================

    @Test
    fun testRejectTruncatedHeader() {
        // Only 41 bytes (less than 42-byte header size)
        val truncated = PHASE_5B_PACKET_0.copyOf(41)

        try {
            LumaPacketCodec.decode(truncated)
            fail("Expected TruncatedPacketException")
        } catch (e: TruncatedPacketException) {
            assertEquals(42, e.expected)
            assertEquals(41, e.actual)
        }
    }

    @Test
    fun testRejectTruncatedPayload() {
        // Header says 80 bytes payload, but provide only 50 bytes of payload (92 bytes total)
        val truncated = PHASE_5B_PACKET_0.copyOf(92)

        try {
            LumaPacketCodec.decode(truncated)
            fail("Expected TruncatedPacketException")
        } catch (e: TruncatedPacketException) {
            assertEquals(122, e.expected)
            assertEquals(92, e.actual)
        }
    }

    // =========================================================================
    // F. Extra / Trailing Bytes Test
    // =========================================================================

    @Test
    fun testRejectTrailingDataByDefault() {
        // 122 bytes + 1 extra byte
        val withTrailing = ByteArray(123)
        System.arraycopy(PHASE_5B_PACKET_0, 0, withTrailing, 0, 122)
        withTrailing[122] = 0xAA.toByte()

        try {
            LumaPacketCodec.decode(withTrailing, allowTrailing = false)
            fail("Expected TrailingDataException")
        } catch (e: TrailingDataException) {
            assertEquals(122, e.expected)
            assertEquals(123, e.actual)
        }
    }

    @Test
    fun testAllowTrailingDataWhenConfigured() {
        val withTrailing = ByteArray(130)
        System.arraycopy(PHASE_5B_PACKET_0, 0, withTrailing, 0, 122)

        val packet = LumaPacketCodec.decode(withTrailing, allowTrailing = true)
        assertEquals(80, packet.payloadLength)
        assertEquals(80, packet.payload.size)
        assertEquals(122, packet.rawBytes.size)
        assertEquals(0x0d2f3c6fL, packet.crc32)
    }

    // =========================================================================
    // G. Payload Length Mismatch Test
    // =========================================================================

    @Test
    fun testPayloadLengthMismatch() {
        val buffer = ByteBuffer.wrap(PHASE_5B_PACKET_0.copyOf()).order(ByteOrder.BIG_ENDIAN)
        // Modify payload length field at byte 36 to claim 100 bytes (packet is only 122)
        buffer.putShort(36, 100.toShort())

        try {
            LumaPacketCodec.decode(buffer.array())
            fail("Expected TruncatedPacketException")
        } catch (e: TruncatedPacketException) {
            assertEquals(142, e.expected) // 42 + 100
            assertEquals(122, e.actual)
        }
    }

    // =========================================================================
    // H. Unsigned Byte Values Test (bytes >= 0x80 and 0xFF)
    // =========================================================================

    @Test
    fun testUnsignedBytesSurviveUnchanged() {
        val testPayload = ByteArray(10) { i ->
            when (i) {
                0 -> 0x80.toByte() // 128
                1 -> 0xFF.toByte() // 255
                2 -> 0xFE.toByte() // 254
                3 -> 0xAA.toByte() // 170
                4 -> 0x7F.toByte() // 127
                5 -> 0x00.toByte() // 0
                else -> (0x80 + i).toByte()
            }
        }

        // Construct synthetic valid packet with high-byte payload
        val raw = ByteArray(42 + testPayload.size)
        val buf = ByteBuffer.wrap(raw).order(ByteOrder.BIG_ENDIAN)
        raw[0] = 0x4C; raw[1] = 0x55; raw[2] = 0x4D; raw[3] = 0x41 // 'LUMA'
        raw[4] = 1 // version 1
        raw[5] = 2 // DATA
        raw[6] = 0x82.toByte() // flags with high bit set (130)
        raw[7] = 0 // reserved
        for (i in 0 until 16) raw[8 + i] = (0x90 + i).toByte()
        buf.putInt(24, 1000)
        buf.putInt(28, 500)
        buf.putShort(32, 16.toShort())
        buf.putShort(34, 1.toShort())
        buf.putShort(36, testPayload.size.toShort())
        System.arraycopy(testPayload, 0, raw, 42, testPayload.size)

        // Compute valid CRC
        val crc = LumaPacketCodec.computePacketChecksum(raw, testPayload.size)
        buf.putInt(38, (crc and 0xFFFFFFFFL).toInt())

        val packet = LumaPacketCodec.decode(raw)
        assertEquals(0x82, packet.flags)
        assertEquals(128, packet.payload[0].toInt() and 0xFF)
        assertEquals(255, packet.payload[1].toInt() and 0xFF)
        assertEquals(254, packet.payload[2].toInt() and 0xFF)
        assertEquals(170, packet.payload[3].toInt() and 0xFF)
        assertArrayEquals(testPayload, packet.payload)
    }

    // =========================================================================
    // I. Big-Endian Fields Parsing Test
    // =========================================================================

    @Test
    fun testBigEndianFieldParsing() {
        val raw = ByteArray(42)
        val buf = ByteBuffer.wrap(raw).order(ByteOrder.BIG_ENDIAN)
        raw[0] = 0x4C; raw[1] = 0x55; raw[2] = 0x4D; raw[3] = 0x41
        raw[4] = 1; raw[5] = 2; raw[6] = 0; raw[7] = 0

        // Asymmetric values to detect endian inversion
        val testBlockIndex = 0x12345678L
        val testSymbolId = 0x89ABCDEFL // High bit set: 2,309,737,967L
        val testK = 0xFEDC // 65244
        val testDegree = 0x4321 // 17185
        val testPayloadLen = 0

        buf.putInt(24, (testBlockIndex and 0xFFFFFFFFL).toInt())
        buf.putInt(28, (testSymbolId and 0xFFFFFFFFL).toInt())
        buf.putShort(32, (testK and 0xFFFF).toShort())
        buf.putShort(34, (testDegree and 0xFFFF).toShort())
        buf.putShort(36, testPayloadLen.toShort())

        val crc = LumaPacketCodec.computePacketChecksum(raw, testPayloadLen)
        buf.putInt(38, (crc and 0xFFFFFFFFL).toInt())

        val packet = LumaPacketCodec.decode(raw)
        assertEquals(0x12345678L, packet.blockIndex)
        assertEquals(0x89ABCDEFL, packet.symbolId)
        assertEquals(0xFEDC, packet.k)
        assertEquals(0x4321, packet.degree)
        assertEquals(0, packet.payloadLength)
        assertEquals(crc, packet.crc32)
    }

    // =========================================================================
    // J. ZXing BYTE_SEGMENTS Extraction Tests
    // =========================================================================

    @Test
    fun testExtractNullResult() {
        assertNull(QrBytePayloadExtractor.extract(null))
    }

    @Test
    fun testExtractMissingMetadata() {
        val result = Result("TEXT_ONLY", null, emptyArray<ResultPoint>(), BarcodeFormat.QR_CODE)
        assertNull(QrBytePayloadExtractor.extract(result))
    }

    @Test
    fun testExtractMissingByteSegments() {
        val result = Result("TEXT_ONLY", null, emptyArray<ResultPoint>(), BarcodeFormat.QR_CODE)
        result.putMetadata(ResultMetadataType.ERROR_CORRECTION_LEVEL, "M")
        assertNull(QrBytePayloadExtractor.extract(result))
    }

    @Test
    fun testNeverUseRawBytesWhenByteSegmentsAbsent() {
        val dummyCodewords = byteArrayOf(1, 2, 3, 4, 5)
        val result = Result("TEXT_ONLY", dummyCodewords, emptyArray<ResultPoint>(), BarcodeFormat.QR_CODE)
        assertNull("Must never use result.rawBytes as protocol payload", QrBytePayloadExtractor.extract(result))
    }

    @Test
    fun testNeverUseTextWhenByteSegmentsAbsent() {
        val result = Result("LUMA_TEXT_FALLBACK", null, emptyArray<ResultPoint>(), BarcodeFormat.QR_CODE)
        assertNull("Must never use result.text as protocol payload", QrBytePayloadExtractor.extract(result))
    }

    @Test
    fun testExtractSingleByteSegment() {
        val payload = PHASE_5B_PACKET_0.copyOf()
        val result = Result("ignored", null, emptyArray<ResultPoint>(), BarcodeFormat.QR_CODE)
        result.putMetadata(ResultMetadataType.BYTE_SEGMENTS, listOf(payload))

        val extracted = QrBytePayloadExtractor.extract(result)
        assertNotNull(extracted)
        assertArrayEquals(payload, extracted)
    }

    @Test
    fun testExtractMultipleByteSegmentsConcatenatedInOrder() {
        val seg1 = PHASE_5B_PACKET_0.copyOfRange(0, 50)
        val seg2 = PHASE_5B_PACKET_0.copyOfRange(50, 122)

        val result = Result("ignored", null, emptyArray<ResultPoint>(), BarcodeFormat.QR_CODE)
        result.putMetadata(ResultMetadataType.BYTE_SEGMENTS, listOf(seg1, seg2))

        val extracted = QrBytePayloadExtractor.extract(result)
        assertNotNull(extracted)
        assertEquals(122, extracted!!.size)
        assertArrayEquals(PHASE_5B_PACKET_0, extracted)

        // Verify the extracted bytes decode as a valid packet
        val packet = LumaPacketCodec.decode(extracted)
        assertEquals(0x0d2f3c6fL, packet.crc32)
        assertEquals(0L, packet.symbolId)
    }

    @Test
    fun testBinaryBytesGreaterThan0x80SurviveWithoutUtf8Corruption() {
        val highBytes = byteArrayOf(0x80.toByte(), 0x90.toByte(), 0xFE.toByte(), 0xFF.toByte(), 0xDE.toByte())
        val result = Result("ignored", null, emptyArray<ResultPoint>(), BarcodeFormat.QR_CODE)
        result.putMetadata(ResultMetadataType.BYTE_SEGMENTS, listOf(highBytes))

        val extracted = QrBytePayloadExtractor.extract(result)
        assertNotNull(extracted)
        assertArrayEquals(highBytes, extracted)

        // Compare with what UTF-8 would have produced: UTF-8 conversion corrupts high bytes
        val utf8Mangled = String(highBytes, Charsets.UTF_8).toByteArray(Charsets.UTF_8)
        assertFalse(
            "Direct BYTE_SEGMENTS extraction must not produce mangled UTF-8 bytes",
            extracted.contentEquals(utf8Mangled)
        )
    }

    // =========================================================================
    // K. Golden Vector Test (Exact Parity with Canonical TypeScript Core)
    // =========================================================================

    @Test
    fun testGoldenVectorPacket0Parity() {
        val packet = LumaPacketCodec.decode(PHASE_5B_PACKET_0)

        // Verify exact header layout fields matching Canonical TS BinaryPacketCodec:
        assertEquals("Protocol version must be 1", 1, packet.version)
        assertEquals("Packet type DATA must be 2", 2, packet.packetType)
        assertEquals("FLAG_ENCRYPTED must be 2", 2, packet.flags)
        assertEquals("Reserved byte must be 0", 0, packet.reserved)
        assertEquals("Session UUID must match fixture manifest", EXPECTED_SESSION_ID, packet.sessionIdUuid)
        assertEquals("Block index must be 0", 0L, packet.blockIndex)
        assertEquals("Symbol ID must be 0", 0L, packet.symbolId)
        assertEquals("Source symbols K must be 16", 16, packet.k)
        assertEquals("LT degree must be 1", 1, packet.degree)
        assertEquals("Payload length must be 80", 80, packet.payloadLength)
        assertEquals("Transmitted CRC must be 0x0d2f3c6f", 0x0d2f3c6fL, packet.crc32)

        // Verify standalone CRC-32 computation
        val computedCrc = LumaPacketCodec.computePacketChecksum(PHASE_5B_PACKET_0, 80)
        assertEquals("Computed CRC must match transmitted CRC", 0x0d2f3c6fL, computedCrc)

        // Verify raw bytes
        assertEquals(122, packet.rawBytes.size)
        assertArrayEquals(PHASE_5B_PACKET_0, packet.rawBytes)
    }

    @Test
    fun testGoldenVectorPacket1Parity() {
        val packet = LumaPacketCodec.decode(PHASE_5B_PACKET_1)

        assertEquals(1, packet.version)
        assertEquals(2, packet.packetType)
        assertEquals(2, packet.flags)
        assertEquals(EXPECTED_SESSION_ID, packet.sessionIdUuid)
        assertEquals(0L, packet.blockIndex)
        assertEquals(1L, packet.symbolId)
        assertEquals(16, packet.k)
        assertEquals(13, packet.degree)
        assertEquals(80, packet.payloadLength)
        assertEquals(0x5d8da80fL, packet.crc32)

        val computedCrc = LumaPacketCodec.computePacketChecksum(PHASE_5B_PACKET_1, 80)
        assertEquals(0x5d8da80fL, computedCrc)
    }

    // =========================================================================
    // Unsupported Protocol Version & Invalid Packet Type
    // =========================================================================

    @Test
    fun testRejectUnsupportedProtocolVersion() {
        val corrupted = PHASE_5B_PACKET_0.copyOf()
        corrupted[4] = 2 // version 2

        try {
            LumaPacketCodec.decode(corrupted)
            fail("Expected UnsupportedProtocolVersionException")
        } catch (e: UnsupportedProtocolVersionException) {
            assertEquals(2, e.version)
        }
    }

    @Test
    fun testRejectInvalidPacketType() {
        val corrupted = PHASE_5B_PACKET_0.copyOf()
        corrupted[5] = 99 // invalid type

        try {
            LumaPacketCodec.decode(corrupted)
            fail("Expected InvalidPacketTypeException")
        } catch (e: InvalidPacketTypeException) {
            assertEquals(99, e.typeCode)
        }
    }
}
