package com.lumalink.harness.crypto

import com.lumalink.harness.LumaPacketCodec
import com.lumalink.harness.fec.LtPacketIntegrationFixture
import com.lumalink.harness.fec.LumaLtDecoder
import com.lumalink.harness.session.LumaManifestCodec
import com.lumalink.harness.session.LumaSessionAnnouncement
import com.lumalink.harness.session.SessionManifestStore
import com.lumalink.harness.transfer.LumaFileReassembler
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import java.security.MessageDigest

/**
 * Requirement 19: End-to-End Dynamic Session Key Bootstrap & Transmission Pipeline Test.
 *
 * Verifies the complete LumaLink lifecycle:
 * MANIFEST
 *   ↓
 * AuthRequest (Receiver → Sender)
 *   ↓
 * Authorization & Key Wrapping (Sender)
 *   ↓
 * AUTH_RESPONSE / KeyEnvelope (Sender → Receiver)
 *   ↓
 * Manifest-Key Invariant Check (Receiver)
 *   ↓
 * Envelope Unwrapping → K_broadcast
 *   ↓
 * Dynamic LumaSecurityContext Establishment
 *   ↓
 * Authenticated AEAD DATA Packets (ChaCha20-Poly1305)
 *   ↓
 * LT Fountain Peeling Decoding
 *   ↓
 * Multi-Block File Reassembly
 *   ↓
 * SHA-256 Digest Verification
 *   ↓
 * FILE OK
 *
 * Runs with ZERO pre-provisioned session keys in PreProvisionedSessionStore.
 */
class ControlEndToEndIntegrationTest {

    private val crypto = AndroidCryptoProvider()
    private val receiverDeviceId = "device-bob"
    private val receiverPrivateKey = TestFixtureSessions.BOB_PRIV
    private val receiverPublicKey = TestFixtureSessions.BOB_PUB

    private val senderDeviceId = "sender-alice"
    private val senderPrivateKey = TestFixtureSessions.ALICE_PRIV
    private val senderPublicKey = TestFixtureSessions.ALICE_PUB

    private val sessionId = TestFixtureSessions.GOLDEN_SESSION_ID_BYTES

    @Before
    fun setUp() {
        PreProvisionedSessionStore.clear()
        SessionManifestStore.clear()
    }

    private fun sha256Hex(data: ByteArray): String {
        val digest = MessageDigest.getInstance("SHA-256").digest(data)
        val sb = StringBuilder(digest.size * 2)
        for (b in digest) {
            val v = b.toInt() and 0xFF
            if (v < 16) sb.append('0')
            sb.append(Integer.toHexString(v))
        }
        return sb.toString()
    }

    @Test
    fun testCompleteDynamicKeyBootstrapAndDataTransferPipeline() {
        // =====================================================================
        // Step 1: Sender Prepares File & Session Parameters
        // =====================================================================
        val originalFileBytes = LtPacketIntegrationFixture.TEST_SOURCE_DATA
        val expectedSha256 = sha256Hex(originalFileBytes)

        val symbolSize = LtPacketIntegrationFixture.SYMBOL_SIZE
        val symbolsPerBlock = LtPacketIntegrationFixture.K
        val totalBlocks = 1

        // Fresh random 32-byte broadcast master secret generated by sender
        val senderMasterBroadcastSecret = ByteArray(32) { i -> ((i * 17 + 41) and 0xFF).toByte() }

        // Sender derives bulk active session keys
        val senderSessionKeys = crypto.deriveSessionKeys(
            sharedSecret = senderMasterBroadcastSecret,
            sessionIdBytes = sessionId,
            infoPrefix = "LumaLink-QuickSend-v2"
        )
        val senderSecurityContext = LumaSecurityContext(
            sessionId = sessionId,
            keys = senderSessionKeys,
            crypto = crypto
        )

        // =====================================================================
        // Step 2: Sender Broadcasts MANIFEST
        // =====================================================================
        val announcement = LumaSessionAnnouncement(
            sessionId = sessionId,
            mode = "quick",
            senderDeviceId = senderDeviceId,
            senderPublicKey = senderPublicKey,
            fileName = "secure-data.bin",
            fileSize = originalFileBytes.size.toLong(),
            sha256Digest = expectedSha256,
            symbolSize = symbolSize,
            symbolsPerBlock = symbolsPerBlock,
            totalBlocks = totalBlocks,
            timestamp = 1728120000000L
        )
        val manifestWirePayload = LumaManifestCodec.encode(announcement)
        val manifestTransportPacket = LumaPacketCodec.encode(
            packetType = LumaPacketCodec.TYPE_MANIFEST,
            flags = 0,
            sessionId = sessionId,
            blockIndex = 0L,
            symbolId = 0L,
            k = 0,
            degree = 0,
            payload = manifestWirePayload
        )

        // Receiver decodes MANIFEST packet and registers metadata dynamically
        val decodedManifestPacket = LumaPacketCodec.decode(manifestTransportPacket)
        val acquiredManifest = LumaManifestCodec.decode(decodedManifestPacket.payload)
        SessionManifestStore.register(acquiredManifest)
        assertTrue(SessionManifestStore.contains(sessionId))

        // Receiver starts with ZERO session keys in PreProvisionedSessionStore!
        assertEquals(0, PreProvisionedSessionStore.count())

        // =====================================================================
        // Step 3: Receiver Generates Binary AUTH_REQUEST
        // =====================================================================
        val authRequest = LumaAuthRequest(
            sessionId = sessionId,
            receiverDeviceId = receiverDeviceId,
            receiverPublicKey = receiverPublicKey,
            timestamp = System.currentTimeMillis()
        )
        val authRequestWirePayload = LumaControlCodec.encodeAuthRequest(authRequest)

        // =====================================================================
        // Step 4: Sender Authorizes & Produces Binary AUTH_RESPONSE / KeyEnvelope
        // =====================================================================
        val decodedAuthRequest = LumaControlCodec.decodeAuthRequest(authRequestWirePayload)
        assertEquals(receiverDeviceId, decodedAuthRequest.receiverDeviceId)

        // Pairwise ECDH + HKDF wrap key
        val pairwiseSecret = crypto.computeSharedSecret(senderPrivateKey, decodedAuthRequest.receiverPublicKey)
        val wrapKey = crypto.hkdf(
            ikm = pairwiseSecret,
            salt = sessionId,
            info = "LumaLink-KeyWrap-v1".toByteArray(Charsets.UTF_8),
            length = 32
        )
        val wrapNonce = ByteArray(12) { i -> ((i * 3 + 5) and 0xFF).toByte() }
        val aad = LumaKeyEnvelopeUnwrapper.buildEnvelopeAad(sessionId, decodedAuthRequest.receiverDeviceId)

        val wireEncrypted = crypto.encryptAead(
            key = wrapKey,
            nonce = wrapNonce,
            plaintext = senderMasterBroadcastSecret,
            aad = aad
        )
        val tag = wireEncrypted.copyOfRange(0, 16)
        val ciphertext = wireEncrypted.copyOfRange(16, 48)

        val keyEnvelope = LumaEncryptedKeyEnvelope(
            targetDeviceId = decodedAuthRequest.receiverDeviceId,
            ephemeralPublicKey = senderPublicKey,
            wrapNonce = wrapNonce,
            wrapTag = tag,
            wrappedCiphertext = ciphertext
        )
        val authResponse = LumaAuthResponse(
            sessionId = sessionId,
            receiverDeviceId = decodedAuthRequest.receiverDeviceId,
            authState = LumaControlCodec.AUTH_STATE_AUTHORIZED,
            keyEnvelope = keyEnvelope
        )
        val authResponseWirePayload = LumaControlCodec.encodeAuthResponse(authResponse)

        val controlTransportPacket = LumaPacketCodec.encode(
            packetType = LumaPacketCodec.TYPE_CONTROL,
            flags = 0,
            sessionId = sessionId,
            blockIndex = 0L,
            symbolId = 1L, // messageId = 1
            k = 0,
            degree = 0,
            payload = authResponseWirePayload
        )

        // =====================================================================
        // Step 5: Receiver Processes CONTROL Packet & Dynamically Unwraps Envelope
        // =====================================================================
        val decodedControlPacket = LumaPacketCodec.decode(controlTransportPacket)
        assertEquals(LumaPacketCodec.TYPE_CONTROL, decodedControlPacket.packetType)
        assertEquals(1L, decodedControlPacket.symbolId) // messageId

        val decodedAuthResponse = LumaControlCodec.decodeAuthResponse(decodedControlPacket.payload)
        assertTrue(decodedAuthResponse.isAuthorized)
        assertNotNull(decodedAuthResponse.keyEnvelope)

        val unwrapper = LumaKeyEnvelopeUnwrapper(
            localDeviceId = receiverDeviceId,
            localPrivateKey = receiverPrivateKey,
            crypto = crypto
        )

        val unwrapResult = unwrapper.unwrapAndRegister(
            envelope = decodedAuthResponse.keyEnvelope!!,
            manifest = acquiredManifest,
            rawEnvelopePayload = decodedControlPacket.payload
        )

        assertTrue(unwrapResult is KeyEnvelopeUnwrapResult.Accepted)
        val acceptedResult = unwrapResult as KeyEnvelopeUnwrapResult.Accepted
        assertArrayEquals(senderMasterBroadcastSecret, acceptedResult.broadcastSecret)

        // PreProvisionedSessionStore now dynamically contains the security context!
        assertNotNull(PreProvisionedSessionStore.get(sessionId))

        // =====================================================================
        // Step 6: Sender Emits DATA Packets & Receiver Decodes and Reassembles File
        // =====================================================================
        val ltDecoder = LumaLtDecoder(defaultSymbolSize = symbolSize)
        val fileReassembler = LumaFileReassembler(acquiredManifest.toFileManifest())

        // Transmit 24 fountain symbols (sufficient for K=16 peeling recovery)
        val symbolBudget = 24
        for (s in 0 until symbolBudget) {
            val (degree, symData) = LtPacketIntegrationFixture.generateSymbolData(s.toLong())

            // Encrypt symbol payload using ChaCha20-Poly1305 with AAD binding
            val wirePayload = senderSecurityContext.encryptToWirePayload(
                blockIndex = 0L,
                symbolId = s.toLong(),
                plaintext = symData,
                packetTypeCode = LumaPacketCodec.TYPE_DATA,
                flags = LumaPacketCodec.FLAG_ENCRYPTED,
                direction = "sender"
            )

            val dataTransportPacket = LumaPacketCodec.encode(
                packetType = LumaPacketCodec.TYPE_DATA,
                flags = LumaPacketCodec.FLAG_ENCRYPTED,
                sessionId = sessionId,
                blockIndex = 0L,
                symbolId = s.toLong(),
                k = symbolsPerBlock,
                degree = degree,
                payload = wirePayload
            )

            // Receiver decodes packet
            val incomingPacket = LumaPacketCodec.decode(dataTransportPacket)
            val receiverContext = PreProvisionedSessionStore.get(incomingPacket.sessionId)
            assertNotNull("Security context must be available", receiverContext)

            val decryptedSymbol = receiverContext!!.decryptFromWirePayload(
                blockIndex = incomingPacket.blockIndex,
                symbolId = incomingPacket.symbolId,
                wirePayload = incomingPacket.payload,
                packetTypeCode = incomingPacket.packetType,
                flags = incomingPacket.flags,
                checkReplay = true,
                direction = "sender"
            )

            ltDecoder.addSymbol(
                blockIndex = incomingPacket.blockIndex,
                symbolId = incomingPacket.symbolId,
                k = incomingPacket.k,
                data = decryptedSymbol,
                degree = incomingPacket.degree
            )

            if (ltDecoder.isBlockComplete(0L)) {
                val reconstructedBlock = ltDecoder.reconstructBlock(0L)
                assertNotNull(reconstructedBlock)
                fileReassembler.addBlock(0L, reconstructedBlock!!)
                break
            }
        }

        assertTrue("File reassembler must be complete", fileReassembler.isComplete())
        val reassemblyResult = fileReassembler.reassemble()

        assertArrayEquals("Recovered bytes must match original file", originalFileBytes, reassemblyResult.fileBytes)
        assertEquals("SHA-256 digest must match original digest", expectedSha256, reassemblyResult.sha256Digest)
    }
}
