package com.lumalink.harness.crypto

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Android unit tests and cross-platform golden vector compatibility tests for [LumaControlCodec].
 * Validates byte-for-byte fidelity against canonical TypeScript [ControlCodec].
 */
class LumaControlCodecTest {

    companion object {
        fun hexToBytes(hex: String): ByteArray {
            val clean = hex.replace(" ", "").trim()
            val len = clean.length
            val data = ByteArray(len / 2)
            var i = 0
            while (i < len) {
                data[i / 2] = ((Character.digit(clean[i], 16) shl 4) + Character.digit(clean[i + 1], 16)).toByte()
                i += 2
            }
            return data
        }

        fun bytesToHex(bytes: ByteArray): String {
            val sb = StringBuilder(bytes.size * 2)
            for (b in bytes) {
                val v = b.toInt() and 0xFF
                if (v < 16) sb.append('0')
                sb.append(Integer.toHexString(v))
            }
            return sb.toString()
        }

        // Canonical Golden Hex Vectors generated by TypeScript ControlCodec
        const val GOLDEN_AUTH_REQUEST_HEX =
            "0101000009e99973c478442daf602baf76b1d795000001925bfa8e00883186b800b41d5cf0429695da9b3cc4f328ebcd184a6e482fa578c103f06c770a6465766963652d626f62"

        const val GOLDEN_AUTH_RESPONSE_AUTHORIZED_HEX =
            "0201010009e99973c478442daf602baf76b1d7950a6465766963652d626f6207a37cbc142093c8b755dc1b10e86cb426374ad16aa853ed0bdfc0b2b86d1c7c0102030405060708090a0b0c1935484bafc94cd575abf6609c3976dbc13a4d685e8ecb2601828972a12879f2b6d746fd554be3c4bf55eeeefe111b24"

        const val GOLDEN_AUTH_RESPONSE_REJECTED_HEX =
            "0201020509e99973c478442daf602baf76b1d7950a6465766963652d626f62"

        const val GOLDEN_AUTH_RESPONSE_PENDING_HEX =
            "0201030009e99973c478442daf602baf76b1d7950a6465766963652d626f62"
    }

    // =========================================================================
    // AUTH_REQUEST (0x01) Tests
    // =========================================================================

    @Test
    fun testAuthRequestEncodeAndDecodeRoundTrip() {
        val request = LumaAuthRequest(
            sessionId = TestFixtureSessions.GOLDEN_SESSION_ID_BYTES,
            receiverDeviceId = "device-bob",
            receiverPublicKey = TestFixtureSessions.BOB_PUB,
            timestamp = 1728120000000L
        )

        val encoded = LumaControlCodec.encodeAuthRequest(request)
        assertEquals("Total length must be 61 + 10 = 71 bytes", 71, encoded.size)
        assertEquals(LumaControlCodec.TYPE_AUTH_REQUEST, LumaControlCodec.getControlMessageType(encoded))

        val decoded = LumaControlCodec.decodeAuthRequest(encoded)
        assertArrayEquals(request.sessionId, decoded.sessionId)
        assertEquals(request.receiverDeviceId, decoded.receiverDeviceId)
        assertEquals(request.timestamp, decoded.timestamp)
        assertArrayEquals(request.receiverPublicKey, decoded.receiverPublicKey)
    }

    @Test
    fun testAuthRequestTypeScriptGoldenVectorParity() {
        // 1. Decode TypeScript golden hex vector in Kotlin
        val goldenBytes = hexToBytes(GOLDEN_AUTH_REQUEST_HEX)
        val decoded = LumaControlCodec.decodeAuthRequest(goldenBytes)

        assertArrayEquals(TestFixtureSessions.GOLDEN_SESSION_ID_BYTES, decoded.sessionId)
        assertEquals("device-bob", decoded.receiverDeviceId)
        assertEquals(1728120000000L, decoded.timestamp)
        assertArrayEquals(TestFixtureSessions.BOB_PUB, decoded.receiverPublicKey)

        // 2. Encode in Kotlin and verify byte-for-byte identity with TypeScript golden hex
        val reEncoded = LumaControlCodec.encodeAuthRequest(decoded)
        assertEquals(GOLDEN_AUTH_REQUEST_HEX, bytesToHex(reEncoded))
    }

    @Test
    fun testAuthRequestRejectionCases() {
        val validBytes = hexToBytes(GOLDEN_AUTH_REQUEST_HEX)

        // Truncated
        assertThrows(TruncatedControlException::class.java) {
            LumaControlCodec.decodeAuthRequest(validBytes.copyOf(validBytes.size - 1))
        }

        // Trailing data
        assertThrows(TrailingDataControlException::class.java) {
            val withTrailing = ByteArray(validBytes.size + 1)
            System.arraycopy(validBytes, 0, withTrailing, 0, validBytes.size)
            LumaControlCodec.decodeAuthRequest(withTrailing)
        }

        // Unsupported version
        assertThrows(UnsupportedControlVersionException::class.java) {
            val badVersion = validBytes.copyOf()
            badVersion[1] = 99.toByte()
            LumaControlCodec.decodeAuthRequest(badVersion)
        }

        // Non-zero reserved
        assertThrows(MalformedControlException::class.java) {
            val badReserved = validBytes.copyOf()
            badReserved[2] = 0x01.toByte()
            LumaControlCodec.decodeAuthRequest(badReserved)
        }

        // Wrong message type
        assertThrows(InvalidControlMessageTypeException::class.java) {
            val wrongType = validBytes.copyOf()
            wrongType[0] = 0x02.toByte()
            LumaControlCodec.decodeAuthRequest(wrongType)
        }
    }

    // =========================================================================
    // AUTH_RESPONSE / KEY_ENVELOPE (0x02) Tests
    // =========================================================================

    @Test
    fun testAuthResponseAuthorizedTypeScriptGoldenVectorParity() {
        val goldenBytes = hexToBytes(GOLDEN_AUTH_RESPONSE_AUTHORIZED_HEX)
        val decoded = LumaControlCodec.decodeAuthResponse(goldenBytes)

        assertEquals(LumaControlCodec.AUTH_STATE_AUTHORIZED, decoded.authState)
        assertTrue(decoded.isAuthorized)
        assertEquals(0, decoded.reasonCode)
        assertEquals("device-bob", decoded.receiverDeviceId)
        assertArrayEquals(TestFixtureSessions.GOLDEN_SESSION_ID_BYTES, decoded.sessionId)
        assertNotNull(decoded.keyEnvelope)

        val env = decoded.keyEnvelope!!
        assertEquals("device-bob", env.targetDeviceId)
        assertArrayEquals(TestFixtureSessions.ALICE_PUB, env.ephemeralPublicKey)
        assertArrayEquals(hexToBytes("0102030405060708090a0b0c"), env.wrapNonce)
        assertArrayEquals(hexToBytes("1935484bafc94cd575abf6609c3976db"), env.wrapTag)
        assertArrayEquals(hexToBytes("c13a4d685e8ecb2601828972a12879f2b6d746fd554be3c4bf55eeeefe111b24"), env.wrappedCiphertext)

        // Re-encode in Kotlin and check byte-for-byte identity
        val reEncoded = LumaControlCodec.encodeAuthResponse(decoded)
        assertEquals(GOLDEN_AUTH_RESPONSE_AUTHORIZED_HEX, bytesToHex(reEncoded))
    }

    @Test
    fun testAuthResponseRejectedTypeScriptGoldenVectorParity() {
        val goldenBytes = hexToBytes(GOLDEN_AUTH_RESPONSE_REJECTED_HEX)
        val decoded = LumaControlCodec.decodeAuthResponse(goldenBytes)

        assertEquals(LumaControlCodec.AUTH_STATE_REJECTED, decoded.authState)
        assertTrue(decoded.isRejected)
        assertEquals(5, decoded.reasonCode)
        assertEquals("device-bob", decoded.receiverDeviceId)
        assertNull(decoded.keyEnvelope)

        val reEncoded = LumaControlCodec.encodeAuthResponse(decoded)
        assertEquals(GOLDEN_AUTH_RESPONSE_REJECTED_HEX, bytesToHex(reEncoded))
    }

    @Test
    fun testAuthResponsePendingTypeScriptGoldenVectorParity() {
        val goldenBytes = hexToBytes(GOLDEN_AUTH_RESPONSE_PENDING_HEX)
        val decoded = LumaControlCodec.decodeAuthResponse(goldenBytes)

        assertEquals(LumaControlCodec.AUTH_STATE_PENDING, decoded.authState)
        assertTrue(decoded.isPending)
        assertEquals(0, decoded.reasonCode)
        assertNull(decoded.keyEnvelope)

        val reEncoded = LumaControlCodec.encodeAuthResponse(decoded)
        assertEquals(GOLDEN_AUTH_RESPONSE_PENDING_HEX, bytesToHex(reEncoded))
    }

    @Test
    fun testAuthResponseRejectionCases() {
        val validBytes = hexToBytes(GOLDEN_AUTH_RESPONSE_AUTHORIZED_HEX)

        // Truncated envelope
        assertThrows(TruncatedControlException::class.java) {
            LumaControlCodec.decodeAuthResponse(validBytes.copyOf(validBytes.size - 10))
        }

        // Trailing bytes
        assertThrows(TrailingDataControlException::class.java) {
            val withTrailing = ByteArray(validBytes.size + 2)
            System.arraycopy(validBytes, 0, withTrailing, 0, validBytes.size)
            LumaControlCodec.decodeAuthResponse(withTrailing)
        }

        // Invalid auth state
        assertThrows(InvalidControlFieldException::class.java) {
            val badState = validBytes.copyOf()
            badState[2] = 99.toByte()
            LumaControlCodec.decodeAuthResponse(badState)
        }
    }
}
